"""Install the Rust backend as a drop-in replacement for v0.5's C extension.

This script:
1. Backs up the existing _c_tet_index.cpython-*.so
2. Creates a Python wrapper _c_tet_index.py that imports from iref3d_core
3. v0.5 will automatically use Rust for tet_index_series and poly_convolve

Usage:
    python3 data/install_rust_backend.py [--uninstall]
"""
from __future__ import annotations

import argparse
import glob
import os
import shutil
import sys
from pathlib import Path

V05_SRC = os.environ.get(
    "IREF3D_V05_SRC",
    "/Users/pmp/Documents/Research/ultimate/v0.5/src",
)
C_KERNEL_DIR = Path(V05_SRC) / "manifold_index" / "core" / "_c_kernel"
RUST_LIB = Path(__file__).resolve().parent.parent / "core" / "target" / "release"

WRAPPER_CONTENT = '''"""Rust drop-in replacement for the C tet_index extension.

Auto-generated by iref3d/data/install_rust_backend.py.
Imports tet_index_series, tet_degree_x2, poly_convolve from the Rust
iref3d_core module instead of the C extension.
"""
import sys as _sys

# Add Rust lib to path if needed
_rust_lib = "{rust_lib}"
if _rust_lib not in _sys.path:
    _sys.path.insert(0, _rust_lib)

from iref3d_core import tet_index_series, tet_degree_x2, poly_convolve
'''


def install():
    if not C_KERNEL_DIR.exists():
        print(f"Error: _c_kernel dir not found: {C_KERNEL_DIR}", file=sys.stderr)
        return 1

    # Check Rust lib exists
    dylib = RUST_LIB / "libiref3d_core.dylib"
    if not dylib.exists():
        print(f"Error: Rust library not found: {dylib}", file=sys.stderr)
        print("Build with: cd core && cargo build --features python --release")
        return 1

    # Back up existing .so files
    so_files = glob.glob(str(C_KERNEL_DIR / "_c_tet_index.cpython-*.so"))
    for so in so_files:
        backup = so + ".bak"
        if not os.path.exists(backup):
            shutil.move(so, backup)
            print(f"  Backed up: {Path(so).name} → {Path(backup).name}")
        else:
            os.remove(so)
            print(f"  Removed: {Path(so).name} (backup exists)")

    # Write Python wrapper
    wrapper_path = C_KERNEL_DIR / "_c_tet_index.py"
    wrapper_path.write_text(WRAPPER_CONTENT.format(rust_lib=str(RUST_LIB)))
    print(f"  Created: {wrapper_path}")

    # Clear __pycache__
    pycache = C_KERNEL_DIR / "__pycache__"
    if pycache.exists():
        shutil.rmtree(pycache)
        print(f"  Cleared: __pycache__")

    print("\nRust backend installed. v0.5 will now use Rust for:")
    print("  - tet_index_series")
    print("  - tet_degree_x2")
    print("  - poly_convolve")
    return 0


def uninstall():
    # Remove wrapper
    wrapper_path = C_KERNEL_DIR / "_c_tet_index.py"
    if wrapper_path.exists():
        os.remove(wrapper_path)
        print(f"  Removed: {wrapper_path}")

    # Restore backups
    bak_files = glob.glob(str(C_KERNEL_DIR / "_c_tet_index.cpython-*.so.bak"))
    for bak in bak_files:
        orig = bak[:-4]  # strip .bak
        shutil.move(bak, orig)
        print(f"  Restored: {Path(orig).name}")

    # Clear __pycache__
    pycache = C_KERNEL_DIR / "__pycache__"
    if pycache.exists():
        shutil.rmtree(pycache)
        print(f"  Cleared: __pycache__")

    print("\nRust backend uninstalled. v0.5 will use the C extension.")
    return 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--uninstall", action="store_true")
    args = ap.parse_args()

    if args.uninstall:
        return uninstall()
    return install()


if __name__ == "__main__":
    raise SystemExit(main())
